---
- name: Install coturn
  ansible.builtin.apt:
    pkg: coturn
    state: present
    cache_valid_time: 3600

- name: Give coturn access to TLS cert
  ansible.builtin.user:
    name: turnserver
    groups: "{{ coturn_tls_group }}"
    append: true
  when: coturn_tls and coturn_tls_group is defined

- name: Enable /etc/default/coturn
  ansible.builtin.lineinfile:
    dest: /etc/default/coturn
    line: TURNSERVER_ENABLED=1
    regexp: "^#?TURNSERVER_ENABLED="

- name: Create parameters for Diffie–Hellman (could take a while)
  ansible.builtin.command: "openssl dhparam -out /etc/coturn-dh-{{ coturn_dhparam_length }}.pem {{ coturn_dhparam_length }}"
  args:
    creates: /etc/coturn-dh-{{ coturn_dhparam_length }}.pem
  when:
    - coturn_tls
    - not coturn_tls_strengh == "modern"
  notify: Restart coturn

- name: Copy coturn config
  ansible.builtin.template:
    dest: /etc/turnserver.conf
    src: turnserver.conf.j2
    owner: root
    group: root
    mode: 0644
  notify: Restart coturn

- name: Include systemd tasks
  ansible.builtin.import_tasks: systemd.yml
  when: ansible_service_mgr == "systemd"

- name: Reload systemd and restart coturn if necessary
  ansible.builtin.meta: flush_handlers

- name: Start coturn
  ansible.builtin.service:
    name: coturn
    state: started

- name: Include goss tasks
  ansible.builtin.include_tasks:
    file: goss.yml
  tags:
    - goss
